drop table if exists comment CASCADE;

create table user_comment(
                             id bigint generated by default as identity,
                             post_id bigint not null,
                             user_name varchar(30) not null,
                             content varchar(300) not null,
                             reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                             primary key (id)
);

drop table if exists member CASCADE;
create table member(
                       id bigint generated by default as identity,
                       user_name varchar(30) not null,
                       age int not null,
                       primary key (id)
);

drop table if exists post CASCADE;
create table post(
                     id bigint generated by default as identity,
                     user_name varchar(30) not null,
                     title varchar(50) not null,
                     post_content varchar(300) not null,
                     reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                     updt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                     primary key (id)
);